routes/web.php
<?php

use App\Http\Controllers\Admin\InstrumentExportController;
use App\Http\Controllers\Admin\InstrumentImportController;
use App\Http\Controllers\Admin\ManufactureController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\InstrumentController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\UserExportController;
use App\Http\Controllers\Admin\UserImportController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\CartController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/telescope', function () {
    return view('telescope');
});


Route::get('locale/{locale}', 'LocaleController@changeLocale')->name('locale');
Route::get('currency/{currencyCode}', 'CurrencyController@changeCurrency')->name('currency');

Route::middleware(['set_locale'])->group(function (){

    Route::name('user.')->group(function(){

        Route::get('/login', function(){
            if(Auth::check()){
                return redirect(route ('instrument.index'));
            }
            return view('login');
        })->name('login');

        Route::post('/login',[LoginController::class, 'login']);

        Route::get('/forgot', [LoginController::class, 'showForgotForm'])->name('forgot');
        Route::post('/forgot_process', [LoginController::class, 'forgot'])->name('forgot_process');

        Route::get('/logout',function(){
            Auth::logout();
            return redirect(route('instrument.index'));
        })->name('logout');

        Route::get('/registration',function (){
            if(Auth::check()){
                return redirect(route('instrument.index'));
            }
            return view('registration');
        })->name('registration');
        Route::post('/registration',[RegisterController::class, 'save']);
    });

    Route::get ('/category', [App\Http\Controllers\CategoryController::class, 'index'])->name('category.index');
    Route::get ('/category/{category}', [App\Http\Controllers\CategoryController::class, 'show'])->name('category.show');

    Route::get ('/instrument', [App\Http\Controllers\InstrumentController::class, 'index'])->name('instrument.index');
    Route::get ('/instrument/{instrument}', [App\Http\Controllers\InstrumentController::class, 'show'])->name('instrument.show');

    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::post('/cart/add/{instrument}', [CartController::class, 'cartAdd'])->name('cart-add');
    Route::post('/cart/remove/{instrument}', [CartController::class, 'cartRemove'])->name('cart-remove');
    Route::get('/cart/place', [CartController::class, 'cartPlace'])->name('cart.place');
    Route::post('/cart/place', [CartController::class, 'cartConfirm'])->name('cart.confirm');

});

Route::middleware(['role:admin'])->name('admin.')->prefix('admin_panel')->group(function () {

    Route::get ('/',function (){
        return view('admin.admin_panel');
    });
    Route ::resource ('/instrument', InstrumentController::class);
    Route ::resource ('/category', CategoryController::class);
    Route ::resource ('/order', OrderController::class);
    Route ::resource ('/manufacture', ManufactureController::class);
    Route ::resource ('/user', UserController::class);
    Route ::resource ('/permission', PermissionController::class);
    Route ::resource ('/role', RoleController::class);

});

Route::get('admin/orders/{id}/send', [OrderController::class, 'sendOrderTableToCustomer'])->name('admin.orders.send');

Route::post('admin/import-instruments', [InstrumentImportController::class, 'import'])->name('admin.import-instruments');
Route::get('admin/export-instruments', [InstrumentExportController::class, 'export'])->name('admin.export-instruments');

Route::post('admin/import-users', [UserImportController::class, 'import'])->name('admin.import-users');
Route::get('admin/export-users', [UserExportController::class, 'export'])->name('admin.export-users');

resources/views/forgot.blade.php
@extends('layouts.main')

@section('title', 'Forgot password')
@section('custom_css')
    <link rel="stylesheet" type="text/css" href="/styles/product.css">
    <link rel="stylesheet" type="text/css" href="/styles/product_responsive.css">
@endsection

@section('content')
    <div class="home">

      <section class="content">
         <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h3 class="m-0">@lang('login.forgot_password')</h3>
                    <div class="card card-primary">
                        <!-- form start -->
                        <form action="{{route('user.forgot_process')}}" method="POST">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="email">@lang('login.email')</label>
                                    <input type="text"
                                           name="email"
                                           value="{{old('email')}}" id="email"
                                           placeholder="@lang('login.enter_email')" class="form-control">
                                    @error('email')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>
                                <button type="submit" class="btn btn-success">@lang('login.send')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
         </div><!-- /.container-fluid -->
      </section>
      </br>
    </div>

@endsection

resources/views/login.blade.php
@extends('layouts.main')

@section('title', 'log in')
@section('custom_css')
    <link rel="stylesheet" type="text/css" href="/styles/product.css">
    <link rel="stylesheet" type="text/css" href="/styles/product_responsive.css">
@endsection

@section('content')
    <div class="home">

      <section class="content">
         <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h3 class="m-0">@lang('login.entering')</h3>
                    <div class="card card-primary">
                        <!-- form start -->
                        <form action="{{route('user.login')}}" method="POST">
                            @csrf

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="email">@lang('login.email')</label>
                                    <input type="text"
                                           name="email"
                                           value="{{old('email')}}" id="email"
                                           placeholder="@lang('login.enter_email')" class="form-control">
                                    @error('email')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="password">@lang('login.password')</label>
                                    <input type="password"
                                           name="password"
                                           value="" id="password"
                                           placeholder="@lang('login.enter_password')"
                                           class="form-control">
                                    @error('password')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>
                            <div>
                                <a href="{{ route ("user.forgot") }}" class="me-3 py-2 text-dark text-decoration-none"
                                   style="font-size:12px">@lang('login.forgot_password')</a>
                            </div>
                            </br>
                            <button type="submit" class="btn btn-success">@lang('login.sign_in')</button>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="{{route ('user.registration')}}">@lang('login.registration')</a>
                    </div>
                            </br>
                        </form>
                    </div>
                </div>
            </div>
        </div>
      </section>
      </br>
    </div>

@endsection

resources/views/registration.blade.php
@extends('layouts.main')

@section('title', 'Registration')
@section('custom_css')
    <link rel="stylesheet" type="text/css" href="/styles/product.css">
    <link rel="stylesheet" type="text/css" href="/styles/product_responsive.css">
@endsection

@section('content')
    <div class="home">

      <section class="content">
         <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                     <h3 class="m-0">@lang('login.registration')</h3>
                     <div class="card card-primary">
                        <!-- form start -->
                        <form action="{{route('user.registration')}}" method="POST">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="first_name">@lang('login.first_name')</label>
                                    <input type="text"
                                           name="first_name"
                                           value="" id="first_name"
                                           class="form-control"
                                           placeholder="@lang('login.enter_first_name')">
                                    @error('first_name')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="last_name">@lang('login.last_name')</label>
                                    <input class="form-control" type="text"
                                           name="last_name"
                                           value="" id="last_name" placeholder="@lang('login.enter_last_name')">
                                    @error('last_name')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="email">@lang('login.email')</label>
                                    <input class="form-control" type="text"
                                           name="email"
                                           value="{{old('email')}}" id="email"
                                           placeholder="@lang('login.enter_email')">
                                    @error('email')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="password">@lang('login.password')</label>
                                    <input type="password"
                                           name="password"
                                           value=""
                                           class="form-control"
                                           id="password"
                                           placeholder="@lang('login.enter_password')">
                                    @error('password')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="password">@lang('login.repeat_password')</label>
                                    <input type="password"
                                           name="password_confirmation"
                                           value=""
                                           class="form-control"
                                           id="password"
                                           placeholder="@lang('login.confirm_password')">
                                    @error('password')
                                    <div class="alert alert-danger"> {{$message}}</div>
                                    @enderror
                                </div>

                            </br>
                            <button type="submit" class="btn btn-success">@lang('login.sign_up')</button>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="{{route ('user.login')}}">
                                @lang('login.sign_in')
                            </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
         </div><!-- /.container-fluid -->
      </section>
      </br>
    </div>

@endsection