routes/web.php
<?php

use App\Http\Controllers\Admin\InstrumentExportController;
use App\Http\Controllers\Admin\InstrumentImportController;
use App\Http\Controllers\Admin\ManufactureController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\InstrumentController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\UserExportController;
use App\Http\Controllers\Admin\UserImportController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\CartController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/telescope', function () {
    return view('telescope');
});


Route::get('locale/{locale}', 'LocaleController@changeLocale')->name('locale');
Route::get('currency/{currencyCode}', 'CurrencyController@changeCurrency')->name('currency');

Route::middleware(['set_locale'])->group(function (){

    Route::name('user.')->group(function(){

        Route::get('/login', function(){
            if(Auth::check()){
                return redirect(route ('instrument.index'));
            }
            return view('login');
        })->name('login');

        Route::post('/login',[LoginController::class, 'login']);

        Route::get('/forgot', [LoginController::class, 'showForgotForm'])->name('forgot');
        Route::post('/forgot_process', [LoginController::class, 'forgot'])->name('forgot_process');

        Route::get('/logout',function(){
            Auth::logout();
            return redirect(route('instrument.index'));
        })->name('logout');

        Route::get('/registration',function (){
            if(Auth::check()){
                return redirect(route('instrument.index'));
            }
            return view('registration');
        })->name('registration');
        Route::post('/registration',[RegisterController::class, 'save']);
    });

    Route::get ('/category', [App\Http\Controllers\CategoryController::class, 'index'])->name('category.index');
    Route::get ('/category/{category}', [App\Http\Controllers\CategoryController::class, 'show'])->name('category.show');

    Route::get ('/instrument', [App\Http\Controllers\InstrumentController::class, 'index'])->name('instrument.index');
    Route::get ('/instrument/{instrument}', [App\Http\Controllers\InstrumentController::class, 'show'])->name('instrument.show');

    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::post('/cart/add/{instrument}', [CartController::class, 'cartAdd'])->name('cart-add');
    Route::post('/cart/remove/{instrument}', [CartController::class, 'cartRemove'])->name('cart-remove');
    Route::get('/cart/place', [CartController::class, 'cartPlace'])->name('cart.place');
    Route::post('/cart/place', [CartController::class, 'cartConfirm'])->name('cart.confirm');

});

Route::middleware(['role:admin'])->name('admin.')->prefix('admin_panel')->group(function () {

    Route::get ('/',function (){
        return view('admin.admin_panel');
    });
    Route ::resource ('/instrument', InstrumentController::class);
    Route ::resource ('/category', CategoryController::class);
    Route ::resource ('/order', OrderController::class);
    Route ::resource ('/manufacture', ManufactureController::class);
    Route ::resource ('/user', UserController::class);
    Route ::resource ('/permission', PermissionController::class);
    Route ::resource ('/role', RoleController::class);

});

Route::get('admin/orders/{id}/send', [OrderController::class, 'sendOrderTableToCustomer'])->name('admin.orders.send');

Route::post('admin/import-instruments', [InstrumentImportController::class, 'import'])->name('admin.import-instruments');
Route::get('admin/export-instruments', [InstrumentExportController::class, 'export'])->name('admin.export-instruments');

Route::post('admin/import-users', [UserImportController::class, 'import'])->name('admin.import-users');
Route::get('admin/export-users', [UserExportController::class, 'export'])->name('admin.export-users');

resources/views/admin/admin_main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> @yield('title-block') - Admin panel </title>
    <link rel="icon" href="{{ asset('images/measurements-tools.png') }}" type="image/x-icon">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/admin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="/admin/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/admin/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/admin/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="/admin/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">

        <div class="sidebar">
            <br>
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">

                    <li class="nav-item">
                        <a href="{{route('instrument.index')}}" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                Site
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="/admin_panel"
                           class="nav-link @if(request()->is('admin_panel') || request()->is('admin_panel')) active @endif">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Main
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.user.index')}}"
                           class="nav-link @if(request()->is('admin_panel/user') || request()->is('admin_panel/user/*')) active @endif">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                Users
                            </p>
                        </a>
                    </li>
                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-tools"></i>
                            <p>
                                Roles
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{route('admin.role.index')}}"
                                   class="nav-link @if(request()->is('admin_panel/role') || request()->is('admin_panel/role/*')) active @endif ">
                                    <p>Roles</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('admin.permission.index')}}"
                                   class="nav-link @if(request()->is('admin_panel/permission') || request()->is('admin_panel/permission/*')) active @endif">
                                    <p>Permisions</p>
                                </a>
                            </li>

                        </ul>
                    </li>

                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-tools"></i>
                            <p>
                                Instruments
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{route('admin.instrument.index')}}"
                                   class="nav-link @if(request()->is('admin_panel/instrument') || request()->is('admin_panel/instrument/*')) active @endif">
                                    <p>Instruments</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('admin.category.index')}}"
                                   class="nav-link @if(request()->is('admin_panel/category') || request()->is('admin_panel/category/*')) active @endif">
                                    <p>Categories</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('admin.manufacture.index')}}"
                                   class="nav-link @if(request()->is('admin_panel/manufacture') || request()->is('admin_panel/manufacture/*')) active @endif">
                                    <p>Manufactures</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a href="{{route('admin.order.index')}}"
                           class="nav-link @if(request()->is('admin_panel/order') || request()->is('admin_panel/order/*')) active @endif">
                            <i class="nav-icon fas fa-address-card"></i>
                            <p>
                                Orders
                            </p>
                        </a>
                    </li>

                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <div class="content-wrapper">
        @yield('content')
    </div>

    <!-- jQuery -->
    <script src="/admin/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/admin/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="/admin/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
{{--    <script src="/admin/plugins/sparklines/sparkline.js"></script>--}}
    <!-- JQVMap -->
    <script src="/admin/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="/admin/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/admin/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="/admin/plugins/moment/moment.min.js"></script>
    <script src="/admin/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="/admin/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/admin/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
{{--    <script src="/admin/dist/js/demo.js"></script>--}}
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{--    <script src="/admin/dist/js/pages/dashboard.js"></script>--}}
</div>
</body>
</html>

resources/views/admin/admin_panel.blade.php
@extends('admin.admin_main')

@section('title-block', 'Main')

@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h2 class="m-0">ADMIN PANEL</h2>
                </div>
            </div>
        </div>
    </div>
    <br>
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>150</h3>

                            <p>Instruments</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="{{route('admin.instrument.index')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>53<sup style="font-size: 20px">%</sup></h3>

                            <p>Manufactures</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="{{route('admin.manufacture.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>22</h3>

                            <p>User Registrations</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="{{route('admin.user.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>65</h3>

                            <p>New orders</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="{{route('admin.order.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
            <!-- /.row -->
            <!-- Main row -->

            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>

@endsection